#CUSTOMER_SHOPPING_BEHAVIOR
#Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount)
From customer_shopping_behavior
group by gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount
from customer_shopping_behavior
where discount_applied = 'YES' and purchase_amount >= (select AVG(purchase_amount) from customer_shopping_behavior);

#Q3. Which are the top 5 products with the highest average review rating;
 select item_purchased,round(AVG(review_rating),2) as average_product_rating 
 from customer_shopping_behavior
 group by item_purchased
 order by AVG(review_rating) desc
 limit 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,round(AVG(purchase_amount),2) as average_Purchase_Amount
from customer_shopping_behavior
WHERE shipping_type in ('Standard','Express')
group by shipping_type

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, 
	COUNT(customer_id) as total_customer,
	ROUND(AVG(purchase_amount),2) as avg_spend,
    ROUND(SUM(purchase_amount),2) as total_revenue
from customer_shopping_behavior
GROUP BY subscription_status
order by avg_spend,total_revenue desc;
 
 #Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
 item_purchased ,
round(100 * sum(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_percentage
FROM
    customer_shopping_behavior
GROUP BY
   item_purchased
ORDER BY
    discount_percentage DESC
LIMIT 5;

#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
SELECT customer_id, previous_purchases,
 CASE 
   WHEN previous_purchases = 1 THEN 'NEW'
   WHEN previous_purchases between 2 and 10 THEN 'Returning'
   ELSE 'Loyal'
END AS customer_segment
FROM customer_shopping_behavior
)
select customer_segment,count(*) as "number of customers"
from customer_type
group by customer_segment

#Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_shopping_behavior
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_behavior
where previous_purchases > 5
group by subscription_status

#Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer_shopping_behavior
group by age_group
order by total_revenue desc;